[package]
name = "learn_rust_tcp_udp"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "server"
path = "src/bin/server.rs"

[[bin]]
name = "client"
path = "src/bin/client.rs"

[features]
default = ["udp"]
tcp = []
udp = []

[dependencies]

